"""cfo_risk_controls_and_hardening

Revision ID: 05d56f42f272
Revises: ed3697d3abab
Create Date: 2026-09-06 04:26:03.518485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05d56f42f272'
down_revision: Union[str, Sequence[str], None] = 'ed3697d3abab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add new values to exception_type enum if PostgreSQL
    op.execute("ALTER TYPE exception_type ADD VALUE IF NOT EXISTS 'VENDOR_BANK_CHANGE_ANOMALY'")
    op.execute("ALTER TYPE exception_type ADD VALUE IF NOT EXISTS 'DATA_INGESTION_GAP'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('human_corrections',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('exception_id', sa.Uuid(), nullable=False),
    sa.Column('close_run_id', sa.Uuid(), nullable=True),
    sa.Column('original_decision', sa.String(length=64), nullable=False),
    sa.Column('human_decision', sa.String(length=64), nullable=False),
    sa.Column('original_confidence', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('calibrated_confidence', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('exception_type', sa.String(length=64), nullable=False),
    sa.Column('policy_version_id', sa.String(length=64), nullable=True),
    sa.Column('reviewer_role', sa.String(length=64), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['close_run_id'], ['close_runs.id'], name=op.f('fk_human_corrections_close_run_id_close_runs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_human_corrections_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exception_id'], ['exceptions.id'], name=op.f('fk_human_corrections_exception_id_exceptions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_human_corrections'))
    )
    op.create_index(op.f('ix_human_corrections_close_run_id'), 'human_corrections', ['close_run_id'], unique=False)
    op.create_index(op.f('ix_human_corrections_company_id'), 'human_corrections', ['company_id'], unique=False)
    op.create_index(op.f('ix_human_corrections_exception_id'), 'human_corrections', ['exception_id'], unique=False)
    op.create_index(op.f('ix_human_corrections_exception_type'), 'human_corrections', ['exception_type'], unique=False)
    op.add_column('audit_events', sa.Column('control_id', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_audit_events_control_id'), 'audit_events', ['control_id'], unique=False)
    op.add_column('exceptions', sa.Column('metadata_json', sa.Text(), nullable=True))
    op.add_column('vendors', sa.Column('previous_bank_account_id', sa.Uuid(), nullable=True))
    op.add_column('vendors', sa.Column('bank_account_changed_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(op.f('fk_vendors_previous_bank_account_id_bank_accounts'), 'vendors', 'bank_accounts', ['previous_bank_account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_vendors_previous_bank_account_id_bank_accounts'), 'vendors', type_='foreignkey')
    op.drop_column('vendors', 'bank_account_changed_at')
    op.drop_column('vendors', 'previous_bank_account_id')
    op.drop_column('exceptions', 'metadata_json')
    op.drop_index(op.f('ix_audit_events_control_id'), table_name='audit_events')
    op.drop_column('audit_events', 'control_id')
    op.drop_index(op.f('ix_human_corrections_exception_type'), table_name='human_corrections')
    op.drop_index(op.f('ix_human_corrections_exception_id'), table_name='human_corrections')
    op.drop_index(op.f('ix_human_corrections_company_id'), table_name='human_corrections')
    op.drop_index(op.f('ix_human_corrections_close_run_id'), table_name='human_corrections')
    op.drop_table('human_corrections')
    # ### end Alembic commands ###
