"""initial schema: tenancy, financial, close-run, exception, audit

Revision ID: 6df469b53f6d
Revises:
Create Date: 2026-09-05 22:30:37.650372

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6df469b53f6d"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_prompt_versions",
        sa.Column("agent_name", sa.String(length=64), nullable=False),
        sa.Column("version_id", sa.String(length=64), nullable=False),
        sa.Column("prompt_config_json", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("deployed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_prompt_versions")),
        sa.UniqueConstraint(
            "agent_name", "version_id", name="uq_agent_prompt_versions_agent_version"
        ),
    )
    op.create_table(
        "companies",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("legal_name", sa.String(length=255), nullable=True),
        sa.Column("tax_id", sa.String(length=64), nullable=True),
        sa.Column("base_currency", sa.String(length=3), nullable=False),
        sa.Column("fiscal_year_end", sa.String(length=5), nullable=True),
        sa.Column("settings_json", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_companies")),
    )
    op.create_index(op.f("ix_companies_tax_id"), "companies", ["tax_id"], unique=False)
    op.create_table(
        "fx_rates",
        sa.Column("base_currency", sa.String(length=3), nullable=False),
        sa.Column("quote_currency", sa.String(length=3), nullable=False),
        sa.Column("rate", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("effective_date", sa.Date(), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fx_rates")),
        sa.UniqueConstraint(
            "base_currency", "quote_currency", "effective_date", name="uq_fx_rates_base_quote_date"
        ),
    )
    op.create_index(
        op.f("ix_fx_rates_effective_date"), "fx_rates", ["effective_date"], unique=False
    )
    op.create_table(
        "policy_versions",
        sa.Column("version_id", sa.String(length=64), nullable=False),
        sa.Column("policy_config_json", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("deployed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_policy_versions")),
        sa.UniqueConstraint("version_id", name=op.f("uq_policy_versions_version_id")),
    )
    op.create_table(
        "bank_accounts",
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("account_name", sa.String(length=255), nullable=False),
        sa.Column("account_number", sa.String(length=64), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_bank_accounts_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bank_accounts")),
    )
    op.create_index(
        op.f("ix_bank_accounts_company_id"), "bank_accounts", ["company_id"], unique=False
    )
    op.create_table(
        "close_runs",
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "CREATED",
                "INGESTING",
                "RECONCILING",
                "INVESTIGATING",
                "VERIFYING",
                "WAITING_FOR_HUMAN",
                "RESOLVING",
                "FINAL_VERIFICATION",
                "READY_TO_CLOSE",
                "CLOSED",
                "FAILED",
                "BLOCKED",
                name="close_run_status",
            ),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("close_summary", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_close_runs_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_close_runs")),
    )
    op.create_index(op.f("ix_close_runs_company_id"), "close_runs", ["company_id"], unique=False)
    op.create_index(op.f("ix_close_runs_status"), "close_runs", ["status"], unique=False)
    op.create_table(
        "customers",
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "OPEN",
                "APPROVED",
                "PAID",
                "PARTIALLY_PAID",
                "POSTED",
                "VOID",
                "CLOSED",
                name="document_status",
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_customers_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_customers")),
    )
    op.create_index(op.f("ix_customers_company_id"), "customers", ["company_id"], unique=False)
    op.create_table(
        "journal_entries",
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("entry_date", sa.Date(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("reference", sa.String(length=128), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "OPEN",
                "APPROVED",
                "PAID",
                "PARTIALLY_PAID",
                "POSTED",
                "VOID",
                "CLOSED",
                name="document_status",
            ),
            nullable=False,
        ),
        sa.Column("source", sa.String(length=64), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_journal_entries_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_journal_entries")),
    )
    op.create_index(
        op.f("ix_journal_entries_company_id"), "journal_entries", ["company_id"], unique=False
    )
    op.create_index(
        op.f("ix_journal_entries_entry_date"), "journal_entries", ["entry_date"], unique=False
    )
    op.create_index(
        op.f("ix_journal_entries_reference"), "journal_entries", ["reference"], unique=False
    )
    op.create_table(
        "ledger_accounts",
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("account_code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("account_type", sa.String(length=32), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_ledger_accounts_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ledger_accounts")),
    )
    op.create_index(
        op.f("ix_ledger_accounts_account_code"), "ledger_accounts", ["account_code"], unique=False
    )
    op.create_index(
        op.f("ix_ledger_accounts_company_id"), "ledger_accounts", ["company_id"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=True),
        sa.Column(
            "role",
            sa.Enum("VIEWER", "ACCOUNTANT", "CONTROLLER", "CFO", "ADMIN", name="role"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_users_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("company_id", "email", name="uq_users_company_email"),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_index(op.f("ix_users_company_id"), "users", ["company_id"], unique=False)
    op.create_table(
        "bank_transactions",
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("bank_account_id", sa.Uuid(), nullable=False),
        sa.Column("transaction_date", sa.Date(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column(
            "direction", sa.Enum("DEBIT", "CREDIT", name="bank_txn_direction"), nullable=False
        ),
        sa.Column("counterparty", sa.String(length=255), nullable=True),
        sa.Column("reference", sa.String(length=128), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "OPEN",
                "APPROVED",
                "PAID",
                "PARTIALLY_PAID",
                "POSTED",
                "VOID",
                "CLOSED",
                name="document_status",
            ),
            nullable=False,
        ),
        sa.Column("journal_entry_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["bank_account_id"],
            ["bank_accounts.id"],
            name=op.f("fk_bank_transactions_bank_account_id_bank_accounts"),
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_bank_transactions_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["journal_entry_id"],
            ["journal_entries.id"],
            name=op.f("fk_bank_transactions_journal_entry_id_journal_entries"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bank_transactions")),
    )
    op.create_index(
        op.f("ix_bank_transactions_bank_account_id"),
        "bank_transactions",
        ["bank_account_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_bank_transactions_company_id"), "bank_transactions", ["company_id"], unique=False
    )
    op.create_index(
        op.f("ix_bank_transactions_reference"), "bank_transactions", ["reference"], unique=False
    )
    op.create_index(
        op.f("ix_bank_transactions_transaction_date"),
        "bank_transactions",
        ["transaction_date"],
        unique=False,
    )
    op.create_table(
        "close_tasks",
        sa.Column("close_run_id", sa.Uuid(), nullable=False),
        sa.Column(
            "task_type",
            sa.Enum(
                "BANK_RECONCILIATION",
                "AP_RECONCILIATION",
                "AR_RECONCILIATION",
                "INVOICE_VALIDATION",
                "PAYMENT_RECONCILIATION",
                "VARIANCE_ANALYSIS",
                "ACCRUAL_REVIEW",
                "EXCEPTION_REVIEW",
                "FINAL_VERIFICATION",
                "CLOSE_PACKAGE",
                name="close_task_type",
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING", "IN_PROGRESS", "COMPLETED", "FAILED", "BLOCKED", name="close_task_status"
            ),
            nullable=False,
        ),
        sa.Column("assigned_to", sa.String(length=255), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("result_summary", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["close_run_id"],
            ["close_runs.id"],
            name=op.f("fk_close_tasks_close_run_id_close_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_close_tasks")),
    )
    op.create_index(
        op.f("ix_close_tasks_close_run_id"), "close_tasks", ["close_run_id"], unique=False
    )
    op.create_table(
        "expense_reports",
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("employee_id", sa.Uuid(), nullable=True),
        sa.Column("report_number", sa.String(length=64), nullable=False),
        sa.Column("expense_date", sa.Date(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("total", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "OPEN",
                "APPROVED",
                "PAID",
                "PARTIALLY_PAID",
                "POSTED",
                "VOID",
                "CLOSED",
                name="document_status",
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_expense_reports_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"], ["users.id"], name=op.f("fk_expense_reports_employee_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_expense_reports")),
    )
    op.create_index(
        op.f("ix_expense_reports_company_id"), "expense_reports", ["company_id"], unique=False
    )
    op.create_index(
        op.f("ix_expense_reports_report_number"), "expense_reports", ["report_number"], unique=False
    )
    op.create_table(
        "journal_entry_lines",
        sa.Column("journal_entry_id", sa.Uuid(), nullable=False),
        sa.Column("ledger_account_id", sa.Uuid(), nullable=False),
        sa.Column("debit", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column("credit", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["journal_entry_id"],
            ["journal_entries.id"],
            name=op.f("fk_journal_entry_lines_journal_entry_id_journal_entries"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["ledger_account_id"],
            ["ledger_accounts.id"],
            name=op.f("fk_journal_entry_lines_ledger_account_id_ledger_accounts"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_journal_entry_lines")),
    )
    op.create_index(
        op.f("ix_journal_entry_lines_journal_entry_id"),
        "journal_entry_lines",
        ["journal_entry_id"],
        unique=False,
    )
    op.create_table(
        "reconciliation_results",
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("close_run_id", sa.Uuid(), nullable=False),
        sa.Column("reconciliation_type", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum("MATCHED", "PARTIAL", "MISMATCH", "MISSING", name="reconciliation_status"),
            nullable=False,
        ),
        sa.Column("confidence", sa.Numeric(precision=6, scale=4), nullable=True),
        sa.Column("financial_impact", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column("fx_conversion_applied", sa.Boolean(), nullable=False),
        sa.Column("details_json", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["close_run_id"],
            ["close_runs.id"],
            name=op.f("fk_reconciliation_results_close_run_id_close_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_reconciliation_results_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reconciliation_results")),
    )
    op.create_index(
        op.f("ix_reconciliation_results_close_run_id"),
        "reconciliation_results",
        ["close_run_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_reconciliation_results_company_id"),
        "reconciliation_results",
        ["company_id"],
        unique=False,
    )
    op.create_table(
        "role_assignments",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("VIEWER", "ACCOUNTANT", "CONTROLLER", "CFO", "ADMIN", name="role"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_role_assignments_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_role_assignments_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_role_assignments")),
        sa.UniqueConstraint(
            "user_id", "company_id", "role", name="uq_role_assignments_user_company_role"
        ),
    )
    op.create_index(
        op.f("ix_role_assignments_company_id"), "role_assignments", ["company_id"], unique=False
    )
    op.create_index(
        op.f("ix_role_assignments_user_id"), "role_assignments", ["user_id"], unique=False
    )
    op.create_table(
        "vendors",
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("tax_id", sa.String(length=64), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "OPEN",
                "APPROVED",
                "PAID",
                "PARTIALLY_PAID",
                "POSTED",
                "VOID",
                "CLOSED",
                name="document_status",
            ),
            nullable=False,
        ),
        sa.Column("bank_account_id", sa.Uuid(), nullable=True),
        sa.Column("risk_metadata_json", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["bank_account_id"],
            ["bank_accounts.id"],
            name=op.f("fk_vendors_bank_account_id_bank_accounts"),
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_vendors_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vendors")),
    )
    op.create_index(op.f("ix_vendors_company_id"), "vendors", ["company_id"], unique=False)
    op.create_index(op.f("ix_vendors_tax_id"), "vendors", ["tax_id"], unique=False)
    op.create_table(
        "contracts",
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("counterparty_id", sa.Uuid(), nullable=True),
        sa.Column("contract_number", sa.String(length=64), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("value", sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "OPEN",
                "APPROVED",
                "PAID",
                "PARTIALLY_PAID",
                "POSTED",
                "VOID",
                "CLOSED",
                name="document_status",
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_contracts_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["counterparty_id"], ["vendors.id"], name=op.f("fk_contracts_counterparty_id_vendors")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contracts")),
    )
    op.create_index(op.f("ix_contracts_company_id"), "contracts", ["company_id"], unique=False)
    op.create_index(
        op.f("ix_contracts_contract_number"), "contracts", ["contract_number"], unique=False
    )
    op.create_table(
        "purchase_orders",
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("vendor_id", sa.Uuid(), nullable=False),
        sa.Column("po_number", sa.String(length=64), nullable=False),
        sa.Column("order_date", sa.Date(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("total", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "OPEN",
                "APPROVED",
                "PAID",
                "PARTIALLY_PAID",
                "POSTED",
                "VOID",
                "CLOSED",
                name="document_status",
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_purchase_orders_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["vendor_id"], ["vendors.id"], name=op.f("fk_purchase_orders_vendor_id_vendors")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_purchase_orders")),
    )
    op.create_index(
        op.f("ix_purchase_orders_company_id"), "purchase_orders", ["company_id"], unique=False
    )
    op.create_index(
        op.f("ix_purchase_orders_po_number"), "purchase_orders", ["po_number"], unique=False
    )
    op.create_table(
        "reconciliation_matches",
        sa.Column("reconciliation_result_id", sa.Uuid(), nullable=False),
        sa.Column("left_ref_type", sa.String(length=64), nullable=False),
        sa.Column("left_ref_id", sa.Uuid(), nullable=False),
        sa.Column("right_ref_type", sa.String(length=64), nullable=False),
        sa.Column("right_ref_id", sa.Uuid(), nullable=False),
        sa.Column("match_type", sa.String(length=32), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["reconciliation_result_id"],
            ["reconciliation_results.id"],
            name=op.f("fk_reconciliation_matches_reconciliation_result_id_reconciliation_results"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reconciliation_matches")),
    )
    op.create_index(
        op.f("ix_reconciliation_matches_reconciliation_result_id"),
        "reconciliation_matches",
        ["reconciliation_result_id"],
        unique=False,
    )
    op.create_table(
        "goods_receipts",
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("po_id", sa.Uuid(), nullable=False),
        sa.Column("receipt_number", sa.String(length=64), nullable=False),
        sa.Column("receipt_date", sa.Date(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "OPEN",
                "APPROVED",
                "PAID",
                "PARTIALLY_PAID",
                "POSTED",
                "VOID",
                "CLOSED",
                name="document_status",
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_goods_receipts_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["po_id"], ["purchase_orders.id"], name=op.f("fk_goods_receipts_po_id_purchase_orders")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_goods_receipts")),
    )
    op.create_index(
        op.f("ix_goods_receipts_company_id"), "goods_receipts", ["company_id"], unique=False
    )
    op.create_index(op.f("ix_goods_receipts_po_id"), "goods_receipts", ["po_id"], unique=False)
    op.create_index(
        op.f("ix_goods_receipts_receipt_number"), "goods_receipts", ["receipt_number"], unique=False
    )
    op.create_table(
        "invoices",
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("vendor_id", sa.Uuid(), nullable=False),
        sa.Column("invoice_number", sa.String(length=64), nullable=False),
        sa.Column("invoice_date", sa.Date(), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("subtotal", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column("tax", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column("total", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "OPEN",
                "APPROVED",
                "PAID",
                "PARTIALLY_PAID",
                "POSTED",
                "VOID",
                "CLOSED",
                name="document_status",
            ),
            nullable=False,
        ),
        sa.Column("source_document_id", sa.String(length=64), nullable=True),
        sa.Column("po_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_invoices_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["po_id"], ["purchase_orders.id"], name=op.f("fk_invoices_po_id_purchase_orders")
        ),
        sa.ForeignKeyConstraint(
            ["vendor_id"], ["vendors.id"], name=op.f("fk_invoices_vendor_id_vendors")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_invoices")),
    )
    op.create_index(op.f("ix_invoices_company_id"), "invoices", ["company_id"], unique=False)
    op.create_index(
        op.f("ix_invoices_invoice_number"), "invoices", ["invoice_number"], unique=False
    )
    op.create_index(op.f("ix_invoices_vendor_id"), "invoices", ["vendor_id"], unique=False)
    op.create_table(
        "purchase_order_lines",
        sa.Column("purchase_order_id", sa.Uuid(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("quantity", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("amount", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["purchase_order_id"],
            ["purchase_orders.id"],
            name=op.f("fk_purchase_order_lines_purchase_order_id_purchase_orders"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_purchase_order_lines")),
    )
    op.create_index(
        op.f("ix_purchase_order_lines_purchase_order_id"),
        "purchase_order_lines",
        ["purchase_order_id"],
        unique=False,
    )
    op.create_table(
        "goods_receipt_lines",
        sa.Column("goods_receipt_id", sa.Uuid(), nullable=False),
        sa.Column("po_line_id", sa.Uuid(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("quantity_received", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["goods_receipt_id"],
            ["goods_receipts.id"],
            name=op.f("fk_goods_receipt_lines_goods_receipt_id_goods_receipts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["po_line_id"],
            ["purchase_order_lines.id"],
            name=op.f("fk_goods_receipt_lines_po_line_id_purchase_order_lines"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_goods_receipt_lines")),
    )
    op.create_index(
        op.f("ix_goods_receipt_lines_goods_receipt_id"),
        "goods_receipt_lines",
        ["goods_receipt_id"],
        unique=False,
    )
    op.create_table(
        "invoice_lines",
        sa.Column("invoice_id", sa.Uuid(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("quantity", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("amount", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column("po_line_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["invoices.id"],
            name=op.f("fk_invoice_lines_invoice_id_invoices"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["po_line_id"],
            ["purchase_order_lines.id"],
            name=op.f("fk_invoice_lines_po_line_id_purchase_order_lines"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_invoice_lines")),
    )
    op.create_index(
        op.f("ix_invoice_lines_invoice_id"), "invoice_lines", ["invoice_id"], unique=False
    )
    op.create_table(
        "payments",
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("vendor_id", sa.Uuid(), nullable=True),
        sa.Column("invoice_id", sa.Uuid(), nullable=True),
        sa.Column("bank_account_id", sa.Uuid(), nullable=True),
        sa.Column("amount", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("payment_date", sa.Date(), nullable=False),
        sa.Column("beneficiary_reference", sa.String(length=128), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "OPEN",
                "APPROVED",
                "PAID",
                "PARTIALLY_PAID",
                "POSTED",
                "VOID",
                "CLOSED",
                name="document_status",
            ),
            nullable=False,
        ),
        sa.Column("bank_transaction_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["bank_account_id"],
            ["bank_accounts.id"],
            name=op.f("fk_payments_bank_account_id_bank_accounts"),
        ),
        sa.ForeignKeyConstraint(
            ["bank_transaction_id"],
            ["bank_transactions.id"],
            name=op.f("fk_payments_bank_transaction_id_bank_transactions"),
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_payments_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["invoice_id"], ["invoices.id"], name=op.f("fk_payments_invoice_id_invoices")
        ),
        sa.ForeignKeyConstraint(
            ["vendor_id"], ["vendors.id"], name=op.f("fk_payments_vendor_id_vendors")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payments")),
    )
    op.create_index(op.f("ix_payments_company_id"), "payments", ["company_id"], unique=False)
    op.create_index(op.f("ix_payments_invoice_id"), "payments", ["invoice_id"], unique=False)
    op.create_table(
        "exceptions",
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("close_run_id", sa.Uuid(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "DUPLICATE_INVOICE",
                "PO_MISMATCH",
                "RECEIPT_MISMATCH",
                "PAYMENT_MISMATCH",
                "BANK_GL_MISMATCH",
                "MISSING_DOCUMENT",
                "DUPLICATE_PAYMENT",
                "UNUSUAL_VENDOR_ACTIVITY",
                "PAYMENT_FRAGMENTATION",
                "AR_MISMATCH",
                "ACCRUAL_ANOMALY",
                "GL_MAPPING_ERROR",
                "CASH_ANOMALY",
                "OTHER",
                name="exception_type",
            ),
            nullable=False,
        ),
        sa.Column(
            "severity",
            sa.Enum("LOW", "MEDIUM", "HIGH", "CRITICAL", name="exception_severity"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "OPEN",
                "INVESTIGATING",
                "RESOLVED",
                "ESCALATED",
                "REOPENED",
                "AUTO_RESOLVED",
                name="exception_status",
            ),
            nullable=False,
        ),
        sa.Column("financial_impact", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=6, scale=4), nullable=True),
        sa.Column("calibrated_confidence", sa.Numeric(precision=6, scale=4), nullable=True),
        sa.Column("root_cause", sa.Text(), nullable=True),
        sa.Column("recommended_action", sa.Text(), nullable=True),
        sa.Column(
            "autonomy_level",
            sa.Enum("OBSERVE", "RECOMMEND", "STAGE", "EXECUTE", name="autonomy_level"),
            nullable=False,
        ),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("assigned_to", sa.String(length=255), nullable=True),
        sa.Column("source_invoice_id", sa.Uuid(), nullable=True),
        sa.Column("source_po_id", sa.Uuid(), nullable=True),
        sa.Column("source_receipt_id", sa.Uuid(), nullable=True),
        sa.Column("source_payment_id", sa.Uuid(), nullable=True),
        sa.Column("source_bank_txn_id", sa.Uuid(), nullable=True),
        sa.Column("source_journal_entry_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["close_run_id"],
            ["close_runs.id"],
            name=op.f("fk_exceptions_close_run_id_close_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_exceptions_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_bank_txn_id"],
            ["bank_transactions.id"],
            name=op.f("fk_exceptions_source_bank_txn_id_bank_transactions"),
        ),
        sa.ForeignKeyConstraint(
            ["source_invoice_id"],
            ["invoices.id"],
            name=op.f("fk_exceptions_source_invoice_id_invoices"),
        ),
        sa.ForeignKeyConstraint(
            ["source_journal_entry_id"],
            ["journal_entries.id"],
            name=op.f("fk_exceptions_source_journal_entry_id_journal_entries"),
        ),
        sa.ForeignKeyConstraint(
            ["source_payment_id"],
            ["payments.id"],
            name=op.f("fk_exceptions_source_payment_id_payments"),
        ),
        sa.ForeignKeyConstraint(
            ["source_po_id"],
            ["purchase_orders.id"],
            name=op.f("fk_exceptions_source_po_id_purchase_orders"),
        ),
        sa.ForeignKeyConstraint(
            ["source_receipt_id"],
            ["goods_receipts.id"],
            name=op.f("fk_exceptions_source_receipt_id_goods_receipts"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exceptions")),
    )
    op.create_index(
        op.f("ix_exceptions_close_run_id"), "exceptions", ["close_run_id"], unique=False
    )
    op.create_index(op.f("ix_exceptions_company_id"), "exceptions", ["company_id"], unique=False)
    op.create_index(op.f("ix_exceptions_status"), "exceptions", ["status"], unique=False)
    op.create_index(op.f("ix_exceptions_type"), "exceptions", ["type"], unique=False)
    op.create_table(
        "audit_events",
        sa.Column("company_id", sa.Uuid(), nullable=True),
        sa.Column("close_run_id", sa.Uuid(), nullable=True),
        sa.Column(
            "event_type",
            sa.Enum(
                "EXCEPTION_DECISION",
                "EXCEPTION_CREATED",
                "EXCEPTION_RESOLVED",
                "EXCEPTION_ESCALATED",
                "EXCEPTION_REOPENED",
                "APPROVAL",
                "REVERSAL",
                "CLOSE_RUN_STATE_CHANGE",
                "CLOSE_TASK_STATE_CHANGE",
                "ACTION_EXECUTED",
                "AGENT_RUN_STARTED",
                "AGENT_RUN_COMPLETED",
                "SYSTEM",
                "SEED",
                name="audit_event_type",
            ),
            nullable=False,
        ),
        sa.Column("actor", sa.String(length=255), nullable=True),
        sa.Column("actor_type", sa.String(length=32), nullable=True),
        sa.Column("agent_name", sa.String(length=64), nullable=True),
        sa.Column("agent_prompt_version_id", sa.String(length=64), nullable=True),
        sa.Column("policy_version_id", sa.String(length=64), nullable=True),
        sa.Column("exception_id", sa.Uuid(), nullable=True),
        sa.Column("decision", sa.String(length=64), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("financial_impact", sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("confidence", sa.Numeric(precision=6, scale=4), nullable=True),
        sa.Column("calibrated_confidence", sa.Numeric(precision=6, scale=4), nullable=True),
        sa.Column("evidence_ids_json", sa.Text(), nullable=True),
        sa.Column("metadata_json", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["close_run_id"],
            ["close_runs.id"],
            name=op.f("fk_audit_events_close_run_id_close_runs"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_audit_events_company_id_companies"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["exception_id"],
            ["exceptions.id"],
            name=op.f("fk_audit_events_exception_id_exceptions"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_events")),
    )
    op.create_index(
        op.f("ix_audit_events_close_run_id"), "audit_events", ["close_run_id"], unique=False
    )
    op.create_index(
        op.f("ix_audit_events_company_id"), "audit_events", ["company_id"], unique=False
    )
    op.create_index(
        op.f("ix_audit_events_created_at"), "audit_events", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_audit_events_event_type"), "audit_events", ["event_type"], unique=False
    )
    op.create_index(
        op.f("ix_audit_events_exception_id"), "audit_events", ["exception_id"], unique=False
    )
    op.create_table(
        "exception_actions",
        sa.Column("exception_id", sa.Uuid(), nullable=False),
        sa.Column("action_type", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("payload_json", sa.Text(), nullable=True),
        sa.Column("actor", sa.String(length=255), nullable=True),
        sa.Column("executed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["exception_id"],
            ["exceptions.id"],
            name=op.f("fk_exception_actions_exception_id_exceptions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exception_actions")),
    )
    op.create_index(
        op.f("ix_exception_actions_exception_id"),
        "exception_actions",
        ["exception_id"],
        unique=False,
    )
    op.create_table(
        "exception_evidence",
        sa.Column("exception_id", sa.Uuid(), nullable=False),
        sa.Column("evidence_type", sa.String(length=64), nullable=False),
        sa.Column("evidence_ref_id", sa.Uuid(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["exception_id"],
            ["exceptions.id"],
            name=op.f("fk_exception_evidence_exception_id_exceptions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exception_evidence")),
    )
    op.create_index(
        op.f("ix_exception_evidence_exception_id"),
        "exception_evidence",
        ["exception_id"],
        unique=False,
    )
    op.create_table(
        "reversal_actions",
        sa.Column("exception_action_id", sa.Uuid(), nullable=False),
        sa.Column("exception_id", sa.Uuid(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("reversed_by", sa.String(length=255), nullable=True),
        sa.Column("reversed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["exception_action_id"],
            ["exception_actions.id"],
            name=op.f("fk_reversal_actions_exception_action_id_exception_actions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["exception_id"],
            ["exceptions.id"],
            name=op.f("fk_reversal_actions_exception_id_exceptions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reversal_actions")),
    )
    op.create_index(
        op.f("ix_reversal_actions_exception_action_id"),
        "reversal_actions",
        ["exception_action_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_reversal_actions_exception_id"), "reversal_actions", ["exception_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_reversal_actions_exception_id"), table_name="reversal_actions")
    op.drop_index(op.f("ix_reversal_actions_exception_action_id"), table_name="reversal_actions")
    op.drop_table("reversal_actions")
    op.drop_index(op.f("ix_exception_evidence_exception_id"), table_name="exception_evidence")
    op.drop_table("exception_evidence")
    op.drop_index(op.f("ix_exception_actions_exception_id"), table_name="exception_actions")
    op.drop_table("exception_actions")
    op.drop_index(op.f("ix_audit_events_exception_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_event_type"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_created_at"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_company_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_close_run_id"), table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_index(op.f("ix_exceptions_type"), table_name="exceptions")
    op.drop_index(op.f("ix_exceptions_status"), table_name="exceptions")
    op.drop_index(op.f("ix_exceptions_company_id"), table_name="exceptions")
    op.drop_index(op.f("ix_exceptions_close_run_id"), table_name="exceptions")
    op.drop_table("exceptions")
    op.drop_index(op.f("ix_payments_invoice_id"), table_name="payments")
    op.drop_index(op.f("ix_payments_company_id"), table_name="payments")
    op.drop_table("payments")
    op.drop_index(op.f("ix_invoice_lines_invoice_id"), table_name="invoice_lines")
    op.drop_table("invoice_lines")
    op.drop_index(op.f("ix_goods_receipt_lines_goods_receipt_id"), table_name="goods_receipt_lines")
    op.drop_table("goods_receipt_lines")
    op.drop_index(
        op.f("ix_purchase_order_lines_purchase_order_id"), table_name="purchase_order_lines"
    )
    op.drop_table("purchase_order_lines")
    op.drop_index(op.f("ix_invoices_vendor_id"), table_name="invoices")
    op.drop_index(op.f("ix_invoices_invoice_number"), table_name="invoices")
    op.drop_index(op.f("ix_invoices_company_id"), table_name="invoices")
    op.drop_table("invoices")
    op.drop_index(op.f("ix_goods_receipts_receipt_number"), table_name="goods_receipts")
    op.drop_index(op.f("ix_goods_receipts_po_id"), table_name="goods_receipts")
    op.drop_index(op.f("ix_goods_receipts_company_id"), table_name="goods_receipts")
    op.drop_table("goods_receipts")
    op.drop_index(
        op.f("ix_reconciliation_matches_reconciliation_result_id"),
        table_name="reconciliation_matches",
    )
    op.drop_table("reconciliation_matches")
    op.drop_index(op.f("ix_purchase_orders_po_number"), table_name="purchase_orders")
    op.drop_index(op.f("ix_purchase_orders_company_id"), table_name="purchase_orders")
    op.drop_table("purchase_orders")
    op.drop_index(op.f("ix_contracts_contract_number"), table_name="contracts")
    op.drop_index(op.f("ix_contracts_company_id"), table_name="contracts")
    op.drop_table("contracts")
    op.drop_index(op.f("ix_vendors_tax_id"), table_name="vendors")
    op.drop_index(op.f("ix_vendors_company_id"), table_name="vendors")
    op.drop_table("vendors")
    op.drop_index(op.f("ix_role_assignments_user_id"), table_name="role_assignments")
    op.drop_index(op.f("ix_role_assignments_company_id"), table_name="role_assignments")
    op.drop_table("role_assignments")
    op.drop_index(op.f("ix_reconciliation_results_company_id"), table_name="reconciliation_results")
    op.drop_index(
        op.f("ix_reconciliation_results_close_run_id"), table_name="reconciliation_results"
    )
    op.drop_table("reconciliation_results")
    op.drop_index(op.f("ix_journal_entry_lines_journal_entry_id"), table_name="journal_entry_lines")
    op.drop_table("journal_entry_lines")
    op.drop_index(op.f("ix_expense_reports_report_number"), table_name="expense_reports")
    op.drop_index(op.f("ix_expense_reports_company_id"), table_name="expense_reports")
    op.drop_table("expense_reports")
    op.drop_index(op.f("ix_close_tasks_close_run_id"), table_name="close_tasks")
    op.drop_table("close_tasks")
    op.drop_index(op.f("ix_bank_transactions_transaction_date"), table_name="bank_transactions")
    op.drop_index(op.f("ix_bank_transactions_reference"), table_name="bank_transactions")
    op.drop_index(op.f("ix_bank_transactions_company_id"), table_name="bank_transactions")
    op.drop_index(op.f("ix_bank_transactions_bank_account_id"), table_name="bank_transactions")
    op.drop_table("bank_transactions")
    op.drop_index(op.f("ix_users_company_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_ledger_accounts_company_id"), table_name="ledger_accounts")
    op.drop_index(op.f("ix_ledger_accounts_account_code"), table_name="ledger_accounts")
    op.drop_table("ledger_accounts")
    op.drop_index(op.f("ix_journal_entries_reference"), table_name="journal_entries")
    op.drop_index(op.f("ix_journal_entries_entry_date"), table_name="journal_entries")
    op.drop_index(op.f("ix_journal_entries_company_id"), table_name="journal_entries")
    op.drop_table("journal_entries")
    op.drop_index(op.f("ix_customers_company_id"), table_name="customers")
    op.drop_table("customers")
    op.drop_index(op.f("ix_close_runs_status"), table_name="close_runs")
    op.drop_index(op.f("ix_close_runs_company_id"), table_name="close_runs")
    op.drop_table("close_runs")
    op.drop_index(op.f("ix_bank_accounts_company_id"), table_name="bank_accounts")
    op.drop_table("bank_accounts")
    op.drop_table("policy_versions")
    op.drop_index(op.f("ix_fx_rates_effective_date"), table_name="fx_rates")
    op.drop_table("fx_rates")
    op.drop_index(op.f("ix_companies_tax_id"), table_name="companies")
    op.drop_table("companies")
    op.drop_table("agent_prompt_versions")
    # ### end Alembic commands ###
