"""financial_composite_indexes

Revision ID: 761c0fe92564
Revises: 6df469b53f6d
Create Date: 2026-09-05 23:01:17.537466

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "761c0fe92564"
down_revision: Union[str, Sequence[str], None] = "6df469b53f6d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_bank_transactions_company_date",
        "bank_transactions",
        ["company_id", "transaction_date"],
        unique=False,
    )
    op.create_index(
        "ix_goods_receipts_company_date",
        "goods_receipts",
        ["company_id", "receipt_date"],
        unique=False,
    )
    op.create_index(
        "ix_invoices_company_date", "invoices", ["company_id", "invoice_date"], unique=False
    )
    op.create_index(
        "ix_journal_entries_company_date",
        "journal_entries",
        ["company_id", "entry_date"],
        unique=False,
    )
    op.create_index(
        "ix_ledger_accounts_company_code",
        "ledger_accounts",
        ["company_id", "account_code"],
        unique=False,
    )
    op.create_index(
        "ix_payments_company_date", "payments", ["company_id", "payment_date"], unique=False
    )
    op.create_index(
        "ix_purchase_orders_company_date",
        "purchase_orders",
        ["company_id", "order_date"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_purchase_orders_company_date", table_name="purchase_orders")
    op.drop_index("ix_payments_company_date", table_name="payments")
    op.drop_index("ix_ledger_accounts_company_code", table_name="ledger_accounts")
    op.drop_index("ix_journal_entries_company_date", table_name="journal_entries")
    op.drop_index("ix_invoices_company_date", table_name="invoices")
    op.drop_index("ix_goods_receipts_company_date", table_name="goods_receipts")
    op.drop_index("ix_bank_transactions_company_date", table_name="bank_transactions")
    # ### end Alembic commands ###
