"""create demo_traces table

Revision ID: ed3697d3abab
Revises: 6739dea15bfb
Create Date: 2026-09-06 01:59:17.987353

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ed3697d3abab"
down_revision: Union[str, Sequence[str], None] = "6739dea15bfb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "demo_traces",
        sa.Column("company_id", sa.Uuid(), nullable=True),
        sa.Column("scenario_key", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("events_json", sa.Text(), nullable=False),
        sa.Column("total_steps", sa.Integer(), nullable=False),
        sa.Column("total_duration_ms", sa.Integer(), nullable=False),
        sa.Column("is_golden", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_demo_traces_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_demo_traces")),
    )
    op.create_index(op.f("ix_demo_traces_company_id"), "demo_traces", ["company_id"], unique=False)
    op.create_index(
        op.f("ix_demo_traces_scenario_key"), "demo_traces", ["scenario_key"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_demo_traces_scenario_key"), table_name="demo_traces")
    op.drop_index(op.f("ix_demo_traces_company_id"), table_name="demo_traces")
    op.drop_table("demo_traces")
    # ### end Alembic commands ###
